### ISSUE TITLE
Internal server error on charts tab

### ISSUE THREAD

**Issue by Ri0n** [daipresents/redmine_version_burndown_charts#4]
Hi
I've configured everything by your README but I got Internal Server Error while trying to open burndown chart tab in project.

```
NoMethodError (undefined method `due_date' for nil:NilClass):
vendor/plugins/redmine_version_burndown_charts/app/controllers /version_burndown_charts_controller.rb:165:in `find_versions'
/usr/lib/ruby/1.8/active_support/callbacks.rb:178:in `send'
/usr/lib/ruby/1.8/active_support/callbacks.rb:178:in `evaluate_method'
/usr/lib/ruby/1.8/active_support/callbacks.rb:166:in `call'
/usr/lib/ruby/1.8/action_controller/filters.rb:225:in `call'
/usr/lib/ruby/1.8/action_controller/filters.rb:629:in `run_before_filters'
/usr/lib/ruby/1.8/action_controller/filters.rb:615:in `call_filters'
/usr/lib/ruby/1.8/action_controller/filters.rb:610:in `perform_action_without_benchmark'
/usr/lib/ruby/1.8/action_controller/benchmarking.rb:68:in   `perform_action_without_rescue'
/usr/lib/ruby/1.8/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
/usr/lib/ruby/1.8/action_controller/rescue.rb:160:in `perform_action_without_flash'
/usr/lib/ruby/1.8/action_controller/flash.rb:146:in `perform_action'
/usr/lib/ruby/1.8/action_controller/base.rb:532:in `send'
/usr/lib/ruby/1.8/action_controller/base.rb:532:in `process_without_filters'
/usr/lib/ruby/1.8/action_controller/filters.rb:606:in `process'
/usr/lib/ruby/1.8/action_controller/base.rb:391:in `process'
/usr/lib/ruby/1.8/action_controller/base.rb:386:in `call'
/usr/lib/ruby/1.8/action_controller/routing/route_set.rb:437:in `call'
/usr/lib/ruby/1.8/action_controller/dispatcher.rb:87:in `dispatch'
/usr/lib/ruby/1.8/action_controller/dispatcher.rb:121:in `_call'
/usr/lib/ruby/1.8/action_controller/dispatcher.rb:130:in `build_middleware_stack'
/usr/lib/ruby/1.8/active_record/query_cache.rb:29:in `call'
/usr/lib/ruby/1.8/active_record/query_cache.rb:29:in `call'
/usr/lib/ruby/1.8/active_record/connection_adapters/abstract  /query_cache.rb:34:in `cache'
/usr/lib/ruby/1.8/active_record/query_cache.rb:9:in `cache'
/usr/lib/ruby/1.8/active_record/query_cache.rb:28:in `call'
/usr/lib/ruby/1.8/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
/usr/lib/ruby/1.8/action_controller/string_coercion.rb:25:in `call'
/usr/lib/ruby/1.8/rack/head.rb:9:in `call'
/usr/lib/ruby/1.8/rack/methodoverride.rb:24:in `call'
/usr/lib/ruby/1.8/action_controller/params_parser.rb:15:in `call'
/usr/lib/ruby/1.8/action_controller/session/cookie_store.rb:93:in `call'
/usr/lib/ruby/1.8/action_controller/failsafe.rb:26:in `call'
/usr/lib/ruby/1.8/rack/lock.rb:11:in `call'
```

**Comment by Ri0n** [comment]
may be its because I've installed open flash chart from master but not 2.1.1

**Comment by Ri0n** [comment]
just tested, doesn't work with 2.1.1 either. the same error.

redmine-1.0.5 ruby-4.5 debian sqeeze

**Comment by daipresents** [comment]
Hi

Sorry I'm late.
I will check my plugin, so please give me your environment information.
Ex. gem, rails, ruby version.

Thanks 
Dai

## 

Dai Fujihara
Sent with Sparrow

**Comment by Ri0n** [comment]
rails 2.3.5-1.2
I'm not sure I will test it further..

**Comment by daipresents** [comment]
Thank you Ri0n.
My plugin was tested redmine 0.8 or 0.9.
So I check on 1.0.x and 1.1.x environment.

**Comment by foozmeat** [comment]
This error occurs if you have no versions with a due date set

**Comment by daipresents** [comment]
Hi,
I has modified for no version problem. Please use master version.
